### ISSUE TITLE
What do Python and Django have to do with one another?

### ISSUE THREAD

**Issue by mattyplo** [mattyplo/A6_Cloud9_Project#2]
We may want to mention something about what Django and Python have to do with one another.  I'm unsure at this point where to go with this though....but it might be pertinent to write about Python and how it ties into Development and Django and our class and such.

**Comment by mattyplo** [comment]
Deseray is working on this issue

**Comment by melvinax** [comment]
I put it in clould 9.  I will come back and put in here.

**Comment by mattyplo** [comment]
Thanks Melvina!

Great work too!

**Comment by DeserayRuiz** [comment]
Hey, I wrote the paragraph portion about Django & Python below. Where can I add this to the page?
Thanks, Des.

Python is a high-level programming framework language that can be used create an object-based dynamic semantics for databases/files. Python is an open source software that can be used by anyone. Python is super easy to use and can help new and seasoned developers to transitions to other programming and web development languages at a faster rate and the transition is easier compared to different software. Python is considered as one of the inexpensive software to use if you are on a budget and/or interested in looking for a software that requires less code to operate.  Python Virtual ENV’s software can used to access Django.  
Django is an open source web application framework language that can be used as an administration system in Python. The Django system has been described as a rapid development and high-performance software.  Django is secured by hiding your site’s source code (except HTML & CSS) from direct internet viewers and prevents the code from being tampered with. This software can be used on a large scale to support a large population base and can handle a lot of internet foot traffic. Django also supports SEO and web developers to work more effectively with its framework and allows for both users to have the best experience. 
Django has been used in Pinterest, Instagram, Nasa & Firefox Help Sites to name a few. Django uses a Model-Template-View (M-T-V) to display their content to users. The Model portion of Django consists of the data access layer that allows consumers to interact, relate and validate their data. The Template portion of the MTV allows for the framework of the software to be displayed in a modern presentation-related way. The View aspect of the MTV allows for the model to display the appropriate template in the most business logical order. Django is mainly used in the concepts of apps and can be transferred to different environments easily.  Django’s ease of building templates allows for it’s applications to be deplorable with less risks. 


Sources: 
https://www.youtube.com/watch?v=D6esTdOLXh4&t=27s – Django Crash Course 
https://worthwhile.com/blog/2016/07/19/django-python-advantages/ - Worthwhile
